services:
  nginx:
    environment:
      - NODEJS_PREVIEW_PORT=${NODEJS_PREVIEW_PORT}
      - REACTJS_PREVIEW_PORT=${REACTJS_PREVIEW_PORT}
  nodejs:
    working_dir: /var/www/html
    volumes:
      - ./../nodejs_app:/var/www/html
  reactjs:
    working_dir: /var/www/html
    volumes:
      - ./../nodejs_app:/var/www/html
