services:
  nginx:
    environment:
      - NODEJS_PREVIEW_PORT=${NODEJS_PREVIEW_PORT}
      - REACTJS_PREVIEW_PORT=${REACTJS_PREVIEW_PORT}
      - NODEJS_PORT=${NODEJS_PORT}
      - REACTJS_PORT=${REACTJS_PORT}
    volumes:
      - ./builds/nginx/${APP_ENV}:/etc/nginx/templates
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - php_backend
      - nodejs_frontend
      - reactjs_frontend
    depends_on:
      - php
      - nodejs
      - reactjs

  nodejs:
    build:
      context: ../
      dockerfile: ./docker/builds/nodejs/Dockerfile.${APP_ENV}
    container_name: nodejs_app_container
    working_dir: /var/www/html
    volumes:
      - ./../nodejs_app:/var/www/html
    ports:
      - "${NODEJS_PORT}:3000"
      - "${NODEJS_PREVIEW_PORT}:3030"
    tty: true
    stdin_open: true
    # comment this line if you don't want to run the frontend automatically
    # or when you are starting the container for the first time
    command: /bin/sh -c "cd /var/www/html/vuejs && npm install && npm run dev"
    networks:
      - nodejs_frontend

  reactjs:
    build:
      context: ../
      dockerfile: ./docker/builds/reactjs/Dockerfile.${APP_ENV}
    container_name: reactjs_app_container
    working_dir: /var/www/html
    volumes:
      - ./../nodejs_app:/var/www/html
    ports:
      - "${REACTJS_PORT}:3003"
      - "${REACTJS_PREVIEW_PORT}:3033"
    tty: true
    stdin_open: true
    # comment this line if you don't want to run the frontend automatically
    # or when you are starting the container for the first time
    command: /bin/sh -c "cd /var/www/html/reactjs && npm install && npm run dev"
    networks:
      - reactjs_frontend
  
  php:
    working_dir: /var/www/html
    volumes:
      - ./../php_app:/var/www/html
    command:
      - php-fpm
    networks:
      - php_backend

  mysql:
    image: mysql:lts-oracle
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - php_backend

  redis:
    image: redis:8.2.1-alpine
    container_name: redis_cache_container
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - php_backend

networks:
  php_backend:
    driver: bridge
  nodejs_frontend:
    driver: bridge
  reactjs_frontend:
    driver: bridge
