services:
  nginx:
    platform: linux/amd64,linux/arm64
    image: johnflorentinodev/portfolio-nginx-registry:${GITHUB_SHA:-latest}

  php:
    platform: linux/amd64,linux/arm64
    image: johnflorentinodev/portfolio-php-registry:${GITHUB_SHA:-latest}
