# 
services:
  nginx:
    build:
      context: ../
      dockerfile: ./docker/builds/nginx/Dockerfile.${APP_ENV}
    container_name: nginx_server_container

  php:
    build:
      context: ../
      dockerfile: ./docker/builds/php/Dockerfile.${APP_ENV}
    container_name: php_app_container
